spring.application.name=helix-cache
server.port=${HELIX_PORT:8081}

#Node Config
helix.node.id=${HELIX_NODE_ID:node-a}
helix.node.host=${HELIX_HOST:localhost}
helix.node.port=${HELIX_PORT:8081}

#Helix Stats
management.endpoints.web.exposure.include=health,info
