spring.application.name=helix-cache
server.port=${HELIX_PORT:8080}

#Node Config
helix.node.id=${HELIX_NODE_ID:node-a}
helix.node.host=${HELIX_HOST:localhost}
helix.node.port=${HELIX_PORT:8080}

#Cluster Config
helix.cluster.replication-factor=3
helix.cluster.write-quorum=2
helix.cluster.read-quorum=2
helix.cluster.nodes[0].id=node-a
helix.cluster.nodes[0].host=node-a
helix.cluster.nodes[0].port=8080

helix.cluster.nodes[1].id=node-b
helix.cluster.nodes[1].host=node-b
helix.cluster.nodes[1].port=8080

helix.cluster.nodes[2].id=node-c
helix.cluster.nodes[2].host=node-c
helix.cluster.nodes[2].port=8080

helix.cluster.nodes[3].id=node-d
helix.cluster.nodes[3].host=node-d
helix.cluster.nodes[3].port=8080

helix.cluster.nodes[4].id=node-e
helix.cluster.nodes[4].host=node-e
helix.cluster.nodes[4].port=8080

#Helix Stats Actuator
management.endpoints.web.exposure.include=health,info
